# Site settings
name: usangu
email: wsw0353@naver.com
url:  https://usnagu.github.io/usangu.github.io/
description: "Usnagu's Blog"
author: "author"
title: "Usnagu"
permalink: pretty Good
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: Usnagu

twitter:
  username: Usangu
